In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = [
    "I love machine learning",
    "Deep learning is powerful",
    "Python is great for data science",
    "Neural networks can classify images",
    "Natural language processing is amazing",
    "I enjoy coding in Python",
    "Data analysis helps in decision making",
    "Artificial intelligence is the future",
    "TensorFlow and PyTorch are popular frameworks",
    "Big data requires efficient algorithms"
]

In [3]:
sent

['I love machine learning',
 'Deep learning is powerful',
 'Python is great for data science',
 'Neural networks can classify images',
 'Natural language processing is amazing',
 'I enjoy coding in Python',
 'Data analysis helps in decision making',
 'Artificial intelligence is the future',
 'TensorFlow and PyTorch are popular frameworks',
 'Big data requires efficient algorithms']

In [4]:
#vocabulary size
voc_size=10000

In [5]:
#One_hot
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[5541, 5074, 5012, 3993],
 [9212, 3993, 6472, 2169],
 [3800, 6472, 5344, 3761, 4198, 5813],
 [6196, 6994, 5136, 5538, 1770],
 [3668, 238, 2843, 6472, 4582],
 [5541, 3592, 806, 4315, 3800],
 [4198, 1389, 1396, 4315, 4811, 9576],
 [5164, 8989, 6472, 5242, 7782],
 [160, 322, 7560, 201, 2987, 3938],
 [1664, 4198, 5438, 2115, 4503]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=7
emb_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(emb_docs)

[[   0    0    0 5541 5074 5012 3993]
 [   0    0    0 9212 3993 6472 2169]
 [   0 3800 6472 5344 3761 4198 5813]
 [   0    0 6196 6994 5136 5538 1770]
 [   0    0 3668  238 2843 6472 4582]
 [   0    0 5541 3592  806 4315 3800]
 [   0 4198 1389 1396 4315 4811 9576]
 [   0    0 5164 8989 6472 5242 7782]
 [   0  160  322 7560  201 2987 3938]
 [   0    0 1664 4198 5438 2115 4503]]


In [11]:
#feature representaion
dim=10

In [12]:
model = Sequential()
model.add(Embedding(voc_size, dim))
model.build(input_shape=(None, sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 7, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(emb_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step


array([[[ 0.0462676 , -0.03827578,  0.03257925,  0.03244373,
         -0.03535999, -0.03799907,  0.01644632, -0.0189472 ,
          0.00033265,  0.01476607],
        [ 0.0462676 , -0.03827578,  0.03257925,  0.03244373,
         -0.03535999, -0.03799907,  0.01644632, -0.0189472 ,
          0.00033265,  0.01476607],
        [ 0.0462676 , -0.03827578,  0.03257925,  0.03244373,
         -0.03535999, -0.03799907,  0.01644632, -0.0189472 ,
          0.00033265,  0.01476607],
        [ 0.02645243,  0.01000052, -0.00572897,  0.01766534,
         -0.03773922, -0.02059927,  0.03888682,  0.02863747,
         -0.01215135,  0.03729999],
        [-0.01069809, -0.02376946,  0.00193036, -0.02061272,
          0.01824043, -0.04133917,  0.04929749, -0.02927312,
          0.01361288,  0.01980399],
        [ 0.02859357, -0.00616149, -0.03184336, -0.02620267,
         -0.02835226,  0.00798626, -0.01631964,  0.01348932,
          0.0038609 , -0.01812067],
        [ 0.01553741, -0.04648178,  0.02748818,  0.0

In [15]:
emb_docs[0]

array([   0,    0,    0, 5541, 5074, 5012, 3993], dtype=int32)

In [16]:
model.predict(np.array([emb_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([[[ 0.0462676 , -0.03827578,  0.03257925,  0.03244373,
         -0.03535999, -0.03799907,  0.01644632, -0.0189472 ,
          0.00033265,  0.01476607],
        [ 0.0462676 , -0.03827578,  0.03257925,  0.03244373,
         -0.03535999, -0.03799907,  0.01644632, -0.0189472 ,
          0.00033265,  0.01476607],
        [ 0.0462676 , -0.03827578,  0.03257925,  0.03244373,
         -0.03535999, -0.03799907,  0.01644632, -0.0189472 ,
          0.00033265,  0.01476607],
        [ 0.02645243,  0.01000052, -0.00572897,  0.01766534,
         -0.03773922, -0.02059927,  0.03888682,  0.02863747,
         -0.01215135,  0.03729999],
        [-0.01069809, -0.02376946,  0.00193036, -0.02061272,
          0.01824043, -0.04133917,  0.04929749, -0.02927312,
          0.01361288,  0.01980399],
        [ 0.02859357, -0.00616149, -0.03184336, -0.02620267,
         -0.02835226,  0.00798626, -0.01631964,  0.01348932,
          0.0038609 , -0.01812067],
        [ 0.01553741, -0.04648178,  0.02748818,  0.0